keypoints:
  - one
  - two
  - three
viz:
  colormap: viridis
  radius: 5
  text_over_mouse: True
save_image_names: False
autosave: False
save_loc: null
path: null
user_cfg: null
resize_on_each_frame: True

